<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\OperationsController;
use App\Http\Controllers\Adoptions\AdoptionCareController;
use App\Http\Controllers\Adoptions\AdoptionController;
use App\Http\Controllers\Adoptions\AdoptionPickupController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Dashboards\RoleDashboardController;
use App\Http\Controllers\Locations\LocationController;
use App\Http\Controllers\Pets\PetController;
use App\Http\Controllers\Pets\PetFavoritesController;
use App\Http\Controllers\Pets\PetHealthController;
use App\Http\Controllers\Pets\PetSocialController;
use App\Http\Controllers\Profiles\ProfileController;
use App\Http\Controllers\Social\CommunitySafetyController;
use App\Http\Controllers\Social\DirectMessageController;
use App\Http\Controllers\Social\FriendshipController;
use App\Http\Controllers\Social\RealtimeController;
use Illuminate\Support\Facades\Route;

Route::get('pets', [PetController::class, 'index']);
Route::get('pets/{pet}', [PetController::class, 'show']);
Route::get('shelters', [PetController::class, 'shelters']);
Route::get('locations', [LocationController::class, 'index']);
Route::get('community/feed', [ProfileController::class, 'communityFeed']);

Route::post('register', [AuthController::class, 'register'])->middleware('throttle:email-delivery');
Route::middleware(['auth:sanctum', 'active', 'audit', 'community-access'])->group(function () {

    Route::get('favorites', [PetFavoritesController::class, 'index']);
    Route::put('pets/{pet}/favorite', [PetFavoritesController::class, 'store']);
    Route::delete('pets/{pet}/favorite', [PetFavoritesController::class, 'destroy']);
    Route::post('saved-searches', [PetFavoritesController::class, 'saveSearch'])->middleware('throttle:community-writes');
    Route::delete('saved-searches/{search}', [PetFavoritesController::class, 'deleteSearch']);
    Route::get('pets/{pet}/health', [PetHealthController::class, 'index']);
    Route::post('pets/{pet}/health', [PetHealthController::class, 'store'])->middleware('throttle:community-writes');
    Route::delete('pets/{pet}/health/{record}', [PetHealthController::class, 'destroy']);
    Route::get('safety/blocks', [CommunitySafetyController::class, 'index']);
    Route::put('safety/blocks/{user}', [CommunitySafetyController::class, 'block']);
    Route::delete('safety/blocks/{user}', [CommunitySafetyController::class, 'unblock']);
    Route::post('profile/posts/{post}/reports', [CommunitySafetyController::class, 'report'])->middleware('throttle:community-writes');
    Route::patch('adoptions/{adoption}/care', [AdoptionCareController::class, 'update'])->middleware('throttle:community-writes');
    Route::get('admin/operations', [OperationsController::class, 'index']);
    Route::patch('admin/reports/{report}', [OperationsController::class, 'resolve']);
    Route::post('pets/{pet}/adoptions', [AdoptionController::class, 'store'])->middleware('throttle:community-writes');
    Route::post('pets/{pet}/likes', [PetSocialController::class, 'toggleLike'])->middleware('throttle:community-writes');
    Route::get('pets/{pet}/messages', [PetSocialController::class, 'messages']);
    Route::post('pets/{pet}/messages', [PetSocialController::class, 'storeMessage'])->middleware('throttle:community-writes');
    Route::delete('adoptions/{adoption}', [AdoptionController::class, 'destroy']);
    Route::get('profile', [AuthController::class, 'user']);
    Route::put('profile', [AuthController::class, 'updateProfile']);
    Route::get('profile/pet-owners', [ProfileController::class, 'petOwnerOptions']);
    Route::get('profile/social', [ProfileController::class, 'show']);
    Route::get('users/{user}/profile', [ProfileController::class, 'publicProfile']);
    Route::post('users/{user}/friend-requests', [FriendshipController::class, 'send'])->middleware('throttle:community-writes');
    Route::delete('users/{user}/friend-requests', [FriendshipController::class, 'cancel']);
    Route::patch('friend-requests/{friendRequest}', [FriendshipController::class, 'respond']);
    Route::get('notifications', [FriendshipController::class, 'notifications']);
    Route::post('notifications/read', [FriendshipController::class, 'read'])->middleware('throttle:community-writes');
    Route::get('realtime/token', [RealtimeController::class, 'token']);
    Route::get('chat/contacts', [DirectMessageController::class, 'contacts']);
    Route::post('chat/users/{user}', [DirectMessageController::class, 'open'])->middleware('throttle:community-writes');
    Route::get('chat/conversations/{conversation}/messages', [DirectMessageController::class, 'messages']);
    Route::post('chat/conversations/{conversation}/messages', [DirectMessageController::class, 'store'])->middleware('throttle:direct-messages');
    Route::post('chat/conversations/{conversation}/read', [DirectMessageController::class, 'read'])->middleware('throttle:community-writes');
    Route::post('chat/messages/{message}/likes', [DirectMessageController::class, 'toggleLike'])->middleware('throttle:direct-message-likes');
    Route::post('profile/avatar', [ProfileController::class, 'uploadAvatar'])->middleware('throttle:community-writes');
    Route::post('profile/banner', [ProfileController::class, 'uploadBanner'])->middleware('throttle:community-writes');
    Route::delete('profile/avatar', [ProfileController::class, 'removeAvatar']);
    Route::delete('profile/banner', [ProfileController::class, 'removeBanner']);
    Route::post('profile/posts', [ProfileController::class, 'storePost'])->middleware('throttle:community-writes');
    Route::get('profile/posts/{post}', [ProfileController::class, 'showPost']);
    Route::patch('profile/posts/{post}', [ProfileController::class, 'updatePost'])->middleware('throttle:community-writes');
    Route::delete('profile/posts/{post}', [ProfileController::class, 'destroyPost'])->middleware('throttle:community-writes');
    Route::post('profile/pets', [ProfileController::class, 'storeOwnedPet'])->middleware('throttle:community-writes');
    Route::post('profile/pets/{pet}/owners', [ProfileController::class, 'inviteCaretaker'])->middleware('throttle:community-writes');
    Route::delete('profile/pets/{pet}', [ProfileController::class, 'destroyOwnedPet']);
    Route::put('profile/pets/{pet}', [ProfileController::class, 'updateOwnedPet']);
    Route::patch('profile/pets/{pet}/owner-request', [ProfileController::class, 'respondCaretaker']);
    Route::delete('profile/pets/{pet}/owners/me', [ProfileController::class, 'leaveCaretaker']);
    Route::post('profile/posts/{post}/comments', [ProfileController::class, 'storeComment'])->middleware('throttle:community-writes');
    Route::post('profile/posts/{post}/likes', [ProfileController::class, 'togglePostLike'])->middleware('throttle:direct-message-likes');
    Route::get('dashboards/receiver', [RoleDashboardController::class, 'receiver']);
    Route::get('dashboards/donor', [RoleDashboardController::class, 'donor']);
    Route::get('dashboards/admin', [RoleDashboardController::class, 'admin']);
    Route::get('admin/pets', [AdminController::class, 'pets']);
    Route::get('admin/users', [AdminController::class, 'users']);
    Route::put('admin/users/{user}/roles', [AdminController::class, 'updateUserRoles']);
    Route::put('admin/users/{user}/status', [AdminController::class, 'updateUserStatus']);
    Route::get('admin/users/{user}/interests', [AdminController::class, 'userInterests']);
    Route::get('admin/shelters', [AdminController::class, 'shelters']);
    Route::post('admin/shelters', [AdminController::class, 'storeShelter'])->middleware('throttle:community-writes');
    Route::put('admin/shelters/{shelter}', [AdminController::class, 'updateShelter']);
    Route::put('admin/shelters/{shelter}/status', [AdminController::class, 'updateShelterStatus']);
    Route::post('logout', [AuthController::class, 'logout']);
    Route::apiResource('pets', PetController::class)->except(['index', 'show']);
    Route::get('adoptions', [AdoptionController::class, 'index']);
    Route::patch('adoptions/{adoption}', [AdoptionController::class, 'update']);
    Route::post('adoptions/{adoption}/pickup', [AdoptionPickupController::class, 'store'])->middleware('throttle:10,1');
    Route::patch('adoptions/{adoption}/pickup', [AdoptionPickupController::class, 'store'])->middleware('throttle:10,1');
    Route::post('adoptions/{adoption}/release', [AdoptionPickupController::class, 'update'])->middleware('throttle:5,1');
});
