<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Adoptions\AdoptionController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\Dashboards\RoleDashboardController;
use App\Http\Controllers\Locations\LocationController;
use App\Http\Controllers\Pets\PetController;
use App\Http\Controllers\Pets\PetSocialController;
use App\Http\Controllers\Profiles\ProfileController;
use App\Http\Controllers\Social\DirectMessageController;
use App\Http\Controllers\Social\FriendshipController;
use App\Http\Controllers\Social\RealtimeController;
use Illuminate\Support\Facades\Route;

Route::get('pets', [PetController::class, 'index']);
Route::get('pets/{pet}', [PetController::class, 'show']);
Route::get('shelters', [PetController::class, 'shelters']);
Route::get('locations', [LocationController::class, 'index']);
Route::post('login', [AuthController::class, 'login']);
Route::post('register', [AuthController::class, 'register']);
Route::middleware('auth:sanctum')->group(function () {
    Route::post('pets/{pet}/adoptions', [AdoptionController::class, 'store']);
    Route::post('pets/{pet}/likes', [PetSocialController::class, 'toggleLike']);
    Route::get('pets/{pet}/messages', [PetSocialController::class, 'messages']);
    Route::post('pets/{pet}/messages', [PetSocialController::class, 'storeMessage']);
    Route::delete('adoptions/{adoption}', [AdoptionController::class, 'destroy']);
    Route::get('profile', [AuthController::class, 'user']);
    Route::put('profile', [AuthController::class, 'updateProfile']);
    Route::get('profile/social', [ProfileController::class, 'show']);
    Route::get('users/{user}/profile', [ProfileController::class, 'publicProfile']);
    Route::post('users/{user}/friend-requests', [FriendshipController::class, 'send']);
    Route::delete('users/{user}/friend-requests', [FriendshipController::class, 'cancel']);
    Route::patch('friend-requests/{friendRequest}', [FriendshipController::class, 'respond']);
    Route::get('notifications', [FriendshipController::class, 'notifications']);
    Route::post('notifications/read', [FriendshipController::class, 'read']);
    Route::get('realtime/token', [RealtimeController::class, 'token']);
    Route::get('chat/contacts', [DirectMessageController::class, 'contacts']);
    Route::post('chat/users/{user}', [DirectMessageController::class, 'open']);
    Route::get('chat/conversations/{conversation}/messages', [DirectMessageController::class, 'messages']);
    Route::post('chat/conversations/{conversation}/messages', [DirectMessageController::class, 'store']);
    Route::post('chat/messages/{message}/likes', [DirectMessageController::class, 'toggleLike']);
    Route::post('profile/avatar', [ProfileController::class, 'uploadAvatar']);
    Route::post('profile/banner', [ProfileController::class, 'uploadBanner']);
    Route::delete('profile/avatar', [ProfileController::class, 'removeAvatar']);
    Route::delete('profile/banner', [ProfileController::class, 'removeBanner']);
    Route::post('profile/posts', [ProfileController::class, 'storePost']);
    Route::post('profile/posts/{post}/comments', [ProfileController::class, 'storeComment']);
    Route::get('dashboards/receiver', [RoleDashboardController::class, 'receiver']);
    Route::get('dashboards/donor', [RoleDashboardController::class, 'donor']);
    Route::get('dashboards/admin', [RoleDashboardController::class, 'admin']);
    Route::get('admin/pets', [AdminController::class, 'pets']);
    Route::get('admin/users', [AdminController::class, 'users']);
    Route::put('admin/users/{user}/roles', [AdminController::class, 'updateUserRoles']);
    Route::put('admin/users/{user}/status', [AdminController::class, 'updateUserStatus']);
    Route::get('admin/users/{user}/interests', [AdminController::class, 'userInterests']);
    Route::get('admin/shelters', [AdminController::class, 'shelters']);
    Route::post('admin/shelters', [AdminController::class, 'storeShelter']);
    Route::put('admin/shelters/{shelter}', [AdminController::class, 'updateShelter']);
    Route::put('admin/shelters/{shelter}/status', [AdminController::class, 'updateShelterStatus']);
    Route::post('logout', [AuthController::class, 'logout']);
    Route::apiResource('pets', PetController::class)->except(['index', 'show']);
    Route::get('adoptions', [AdoptionController::class, 'index']);
    Route::patch('adoptions/{adoption}', [AdoptionController::class, 'update']);
});
